---
- hosts: all
  tasks:
    - shell: |
        if ! [[ "$(eval "brew cask list | grep '^{{ item }}$'")" ]] ; then
          brew cask install {{ item }}
        fi
      with_items:
        - google-chrome
        - skype
        - dropbox
        - sourcetree
        - tunnelblick
        - sequel-pro
        - mongohub
        - psequel
        - jumpcut
        - flux
        - the-unarchiver
        - mplayerx
        - utorrent
        - licecap # record gifs from screen
        - libreoffice
        - cyberduck
        - android-file-transfer
        - rescuetime
        - pixlr
        - paragon-ntfs
        - iterm2
        - keeweb
        - franz
        - ccmenu
        - zoomus
        - typora
        - spectacle
        - go2shell
        - the-unarchiver
        - mplayerx
        - purevpn
    - shell: "{{ curdir }}/iterm2/install-settings.sh" # run in Terminal

    - shell: |
        if ! mas list | grep {{ item }}; then
          mas intsall $(mas search {{ item }} | awk '{print $1}' | head -1)
        fi
      with_items:
        - Simplenote
        - Twitter
        - Pocket
        - Keynote
        - Spark
