---
- hosts: all
  tasks:
    - shell: brew update
    - shell: brew tap homebrew/services # e.g. allow 'brew services start mysql' command

    # alt
    - shell: brew tap "codebreakdown/homebrew-oss"
    - shell: brew install codebreakdown/oss/alt

    # apps
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
        fi
      with_items:
        - git
        - openssl
        - rbenv
        - ruby-build
        - cmake
        - ctags
        - go
        - imagemagick
        - leiningen
        - sphinx
        - the_silver_searcher
        - python3
        - neovim/neovim/neovim
        - wget
        - sshrc
        - fzf
        - node
        - unar
        - findutils # to use gfind with -print option
        - logstash
        - elixir
        - tmux-cssh
        - httpie

    # java for Elasticsearch
    - shell: brew cask list | grep '^java$'
      ignore_errors: true
      register: java_exists
    - shell: java_exists
      when: java_exists|failed

    # to avoid using flag --with-openssl-dir=/usr/local/opt/openssl
    - shell: brew link --force openssl

    # services
    - shell: |
        if ! [[ "$(brew ls --versions {{ item }})" ]] ; then
          brew install {{ item }}
          ln -sfv /usr/local/opt/{{ item }}/*.plist ~/Library/LaunchAgents
        fi
      with_items:
        - elasticsearch
        - kibana
        - memcached
        - mongodb
        - mysql
        - postgresql
        - redis
        - rabbitmq
        - selenium-server-standalone

    # postgresql
    - shell: createuser -s postgres
      ignore_errors: true

    # ruby
    - file: path=~/.rbenv state=absent
    - file: src=/usr/local/opt/rbenv dest=~/.rbenv state=link

    # - shell: brew install phantomjs # v2 currently does not work with OS X El Capitan, use lines below:
    - shell: npm install phantom phantomjs -g

    # elasticsearch plugins
    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin list | grep 'license$'
      ignore_errors: true
      register: license_exists
    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin install license
      when: license_exists|failed

    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin list | grep 'marvel-agent$'
      ignore_errors: true
      register: marvel_agent_exists
    - shell: /usr/local/Cellar/elasticsearch/*/libexec/bin/plugin install marvel-agent
      when: marvel_agent_exists|failed

    - shell: kibana plugin -l | grep '^sense$'
      ignore_errors: true
      register: sense_exists
    - shell: kibana plugin --install elastic/sense
      when: sense_exists|failed

    - shell: kibana plugin -l | grep '^marvel$'
      ignore_errors: true
      register: marvel_exists
    - shell: kibana plugin --install elasticsearch/marvel/latest
      when: marvel_exists|failed

    - shell: brew services restart elasticsearch
    - shell: brew services restart kibana
